"""

Revision ID: 256e9d27a1f4
Revises: 49d75f1a18b6
Create Date: 2023-10-25 12:27:31.468541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '256e9d27a1f4'
down_revision = '49d75f1a18b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_patient_id_patients'), 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_patient_id_patients'), type_='foreignkey')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
