"""Update appointment table to store doctor id as foreign key

Revision ID: 49d75f1a18b6
Revises: 317b02e418e4
Create Date: 2023-10-24 13:22:00.273036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d75f1a18b6'
down_revision = '317b02e418e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_doctor_id_doctors'), 'doctors', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_doctor_id_doctors'), type_='foreignkey')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
