"""create tree table

Revision ID: 61290d23d7be
Revises: c91e30efc0d0
Create Date: 2023-10-23 13:17:07.119204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61290d23d7be'
down_revision = 'c91e30efc0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leaves', sa.Integer(), nullable=True),
    sa.Column('evergreen', sa.Boolean(), nullable=True),
    sa.Column('fruit', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trees')
    # ### end Alembic commands ###
